services:
  mini-catalogue-backend:
    container_name: mini-catalogue-backend
    build:
      context: ./backend
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_ENV=${APP_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "3000:3000"
    networks:
      - minicatnet
    depends_on:
      - mini-catalogue-db-pg

  mini-catalogue-frontend:
    container_name: mini-catalogue-frontend
    build:
      context: ./frontend/MiniCatalogue
    ports:
      - "4200:80"
    networks:
      - minicatnet
    depends_on:
      - mini-catalogue-backend

  mini-catalogue-db-pg:
    container_name: mini-catalogue-db-pg
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - minicatnet
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  minicatnet:
    driver: bridge

volumes:
  pgdata:
