export enum ErrorEnum {
  INVALID_PARAMETERS = 'INVALID_PARAMETERS',
  GENERIC_SERVER_ERROR = 'GENERIC_SERVER_ERROR',
  INVALID_DATABASE_OBJECT = 'INVALID_DATABASE_OBJECT',
  INVALID_ID = 'INVALID_ID',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  INVALID_TOKEN = 'INVALID_TOKEN',
  NEGATIVE_PRODUCT_PRICE = 'NEGATIVE_PRODUCT_PRICE',
  PRODUCT_NAME_REQUIRED = 'PRODUCT_NAME_REQUIRED',
  CATEGORY_NAME_EMPTY = 'CATEGORY_NAME_EMPTY',
}
